"""add status and interview_date to job_matches

Revision ID: 0369a73f8028
Revises: 34607780bfbb
Create Date: 2026-04-14 15:42:48.909872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0369a73f8028'
down_revision: Union[str, Sequence[str], None] = '34607780bfbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cv_analyses_analyzed_at'), 'cv_analyses', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_cvs_status'), 'cvs', ['status'], unique=False)
    op.add_column('job_matches', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('job_matches', sa.Column('interview_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_job_matches_cv_id'), 'job_matches', ['cv_id'], unique=False)
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_match_score'), 'job_matches', ['match_score'], unique=False)
    op.create_index(op.f('ix_jobs_platform'), 'jobs', ['platform'], unique=False)
    op.create_index(op.f('ix_jobs_scraped_at'), 'jobs', ['scraped_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_scraped_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_platform'), table_name='jobs')
    op.drop_index(op.f('ix_job_matches_match_score'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_cv_id'), table_name='job_matches')
    op.drop_column('job_matches', 'interview_date')
    op.drop_column('job_matches', 'status')
    op.drop_index(op.f('ix_cvs_status'), table_name='cvs')
    op.drop_index(op.f('ix_cv_analyses_analyzed_at'), table_name='cv_analyses')
    # ### end Alembic commands ###
